// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/rpc_shop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckShopPermissionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId    uint64 `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	ProfileId uint64 `protobuf:"varint,2,opt,name=profileId,proto3" json:"profileId,omitempty"`
}

func (x *CheckShopPermissionReq) Reset() {
	*x = CheckShopPermissionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckShopPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckShopPermissionReq) ProtoMessage() {}

func (x *CheckShopPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckShopPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckShopPermissionReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_shop_proto_rawDescGZIP(), []int{0}
}

func (x *CheckShopPermissionReq) GetShopId() uint64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CheckShopPermissionReq) GetProfileId() uint64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type CheckShopPermissionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPermission bool `protobuf:"varint,1,opt,name=isPermission,proto3" json:"isPermission,omitempty"`
}

func (x *CheckShopPermissionRes) Reset() {
	*x = CheckShopPermissionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckShopPermissionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckShopPermissionRes) ProtoMessage() {}

func (x *CheckShopPermissionRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckShopPermissionRes.ProtoReflect.Descriptor instead.
func (*CheckShopPermissionRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_shop_proto_rawDescGZIP(), []int{1}
}

func (x *CheckShopPermissionRes) GetIsPermission() bool {
	if x != nil {
		return x.IsPermission
	}
	return false
}

var File_proto_rpc_shop_proto protoreflect.FileDescriptor

var file_proto_rpc_shop_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x68, 0x6f, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a,
	0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x68, 0x6f, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a,
	0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x68, 0x6f, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69,
	0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x64, 0x0a, 0x0b, 0x53,
	0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x13, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x68, 0x6f, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x68, 0x6f, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x68,
	0x6f, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_shop_proto_rawDescOnce sync.Once
	file_proto_rpc_shop_proto_rawDescData = file_proto_rpc_shop_proto_rawDesc
)

func file_proto_rpc_shop_proto_rawDescGZIP() []byte {
	file_proto_rpc_shop_proto_rawDescOnce.Do(func() {
		file_proto_rpc_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_shop_proto_rawDescData)
	})
	return file_proto_rpc_shop_proto_rawDescData
}

var file_proto_rpc_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rpc_shop_proto_goTypes = []interface{}{
	(*CheckShopPermissionReq)(nil), // 0: proto.CheckShopPermissionReq
	(*CheckShopPermissionRes)(nil), // 1: proto.CheckShopPermissionRes
}
var file_proto_rpc_shop_proto_depIdxs = []int32{
	0, // 0: proto.ShopService.CheckShopPermission:input_type -> proto.CheckShopPermissionReq
	1, // 1: proto.ShopService.CheckShopPermission:output_type -> proto.CheckShopPermissionRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_shop_proto_init() }
func file_proto_rpc_shop_proto_init() {
	if File_proto_rpc_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckShopPermissionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckShopPermissionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_shop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_shop_proto_goTypes,
		DependencyIndexes: file_proto_rpc_shop_proto_depIdxs,
		MessageInfos:      file_proto_rpc_shop_proto_msgTypes,
	}.Build()
	File_proto_rpc_shop_proto = out.File
	file_proto_rpc_shop_proto_rawDesc = nil
	file_proto_rpc_shop_proto_goTypes = nil
	file_proto_rpc_shop_proto_depIdxs = nil
}
