// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/rpc_warehouse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Warehouse
type InsertWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *InsertWarehouseReq) Reset() {
	*x = InsertWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertWarehouseReq) ProtoMessage() {}

func (x *InsertWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertWarehouseReq.ProtoReflect.Descriptor instead.
func (*InsertWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *InsertWarehouseReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type InsertWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InsertWarehouseRes) Reset() {
	*x = InsertWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertWarehouseRes) ProtoMessage() {}

func (x *InsertWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertWarehouseRes.ProtoReflect.Descriptor instead.
func (*InsertWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *InsertWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InsertWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateWarehouseReq) Reset() {
	*x = UpdateWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseReq) ProtoMessage() {}

func (x *UpdateWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseReq.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWarehouseReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWarehouseReq) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateWarehouseRes) Reset() {
	*x = UpdateWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseRes) ProtoMessage() {}

func (x *UpdateWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseRes.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpCountWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *UpCountWarehouseReq) Reset() {
	*x = UpCountWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpCountWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpCountWarehouseReq) ProtoMessage() {}

func (x *UpCountWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpCountWarehouseReq.ProtoReflect.Descriptor instead.
func (*UpCountWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *UpCountWarehouseReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpCountWarehouseReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpCountWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpCountWarehouseRes) Reset() {
	*x = UpCountWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpCountWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpCountWarehouseRes) ProtoMessage() {}

func (x *UpCountWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpCountWarehouseRes.ProtoReflect.Descriptor instead.
func (*UpCountWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{5}
}

func (x *UpCountWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpCountWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpCountWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DownCountWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DownCountWarehouseReq) Reset() {
	*x = DownCountWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownCountWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownCountWarehouseReq) ProtoMessage() {}

func (x *DownCountWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownCountWarehouseReq.ProtoReflect.Descriptor instead.
func (*DownCountWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{6}
}

func (x *DownCountWarehouseReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownCountWarehouseReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DownCountWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DownCountWarehouseRes) Reset() {
	*x = DownCountWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownCountWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownCountWarehouseRes) ProtoMessage() {}

func (x *DownCountWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownCountWarehouseRes.ProtoReflect.Descriptor instead.
func (*DownCountWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{7}
}

func (x *DownCountWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownCountWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DownCountWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Type Warehouse
type InsertTypeInWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   string  `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	WarehouseId uint64  `protobuf:"varint,2,opt,name=warehouseId,proto3" json:"warehouseId,omitempty"`
	HasTag      string  `protobuf:"bytes,3,opt,name=hasTag,proto3" json:"hasTag,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price       float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Count       uint64  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InsertTypeInWarehouseReq) Reset() {
	*x = InsertTypeInWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTypeInWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTypeInWarehouseReq) ProtoMessage() {}

func (x *InsertTypeInWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTypeInWarehouseReq.ProtoReflect.Descriptor instead.
func (*InsertTypeInWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{8}
}

func (x *InsertTypeInWarehouseReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InsertTypeInWarehouseReq) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *InsertTypeInWarehouseReq) GetHasTag() string {
	if x != nil {
		return x.HasTag
	}
	return ""
}

func (x *InsertTypeInWarehouseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertTypeInWarehouseReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InsertTypeInWarehouseReq) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type InsertTypeInWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InsertTypeInWarehouseRes) Reset() {
	*x = InsertTypeInWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTypeInWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTypeInWarehouseRes) ProtoMessage() {}

func (x *InsertTypeInWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTypeInWarehouseRes.ProtoReflect.Descriptor instead.
func (*InsertTypeInWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{9}
}

func (x *InsertTypeInWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertTypeInWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InsertTypeInWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateTypeInWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateTypeInWarehouseReq) Reset() {
	*x = UpdateTypeInWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTypeInWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeInWarehouseReq) ProtoMessage() {}

func (x *UpdateTypeInWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeInWarehouseReq.ProtoReflect.Descriptor instead.
func (*UpdateTypeInWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTypeInWarehouseReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTypeInWarehouseReq) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateTypeInWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateTypeInWarehouseRes) Reset() {
	*x = UpdateTypeInWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTypeInWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeInWarehouseRes) ProtoMessage() {}

func (x *UpdateTypeInWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeInWarehouseRes.ProtoReflect.Descriptor instead.
func (*UpdateTypeInWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTypeInWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTypeInWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateTypeInWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpCountTypeInWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *UpCountTypeInWarehouseReq) Reset() {
	*x = UpCountTypeInWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpCountTypeInWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpCountTypeInWarehouseReq) ProtoMessage() {}

func (x *UpCountTypeInWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpCountTypeInWarehouseReq.ProtoReflect.Descriptor instead.
func (*UpCountTypeInWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{12}
}

func (x *UpCountTypeInWarehouseReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpCountTypeInWarehouseReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpCountTypeInWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpCountTypeInWarehouseRes) Reset() {
	*x = UpCountTypeInWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpCountTypeInWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpCountTypeInWarehouseRes) ProtoMessage() {}

func (x *UpCountTypeInWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpCountTypeInWarehouseRes.ProtoReflect.Descriptor instead.
func (*UpCountTypeInWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{13}
}

func (x *UpCountTypeInWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpCountTypeInWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpCountTypeInWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DownCountTypeInWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DownCountTypeInWarehouseReq) Reset() {
	*x = DownCountTypeInWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownCountTypeInWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownCountTypeInWarehouseReq) ProtoMessage() {}

func (x *DownCountTypeInWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownCountTypeInWarehouseReq.ProtoReflect.Descriptor instead.
func (*DownCountTypeInWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{14}
}

func (x *DownCountTypeInWarehouseReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownCountTypeInWarehouseReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DownCountTypeInWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DownCountTypeInWarehouseRes) Reset() {
	*x = DownCountTypeInWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownCountTypeInWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownCountTypeInWarehouseRes) ProtoMessage() {}

func (x *DownCountTypeInWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownCountTypeInWarehouseRes.ProtoReflect.Descriptor instead.
func (*DownCountTypeInWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{15}
}

func (x *DownCountTypeInWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownCountTypeInWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DownCountTypeInWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId         string `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	WarehouseId       uint64 `protobuf:"varint,2,opt,name=warehouseId,proto3" json:"warehouseId,omitempty"`
	TypeInWarehouseId uint64 `protobuf:"varint,3,opt,name=typeInWarehouseId,proto3" json:"typeInWarehouseId,omitempty"`
	Amount            uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{16}
}

func (x *Order) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Order) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *Order) GetTypeInWarehouseId() uint64 {
	if x != nil {
		return x.TypeInWarehouseId
	}
	return 0
}

func (x *Order) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CountPriceOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupOrderId uint64   `protobuf:"varint,1,opt,name=groupOrderId,proto3" json:"groupOrderId,omitempty"`
	Orders       []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *CountPriceOrderReq) Reset() {
	*x = CountPriceOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountPriceOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPriceOrderReq) ProtoMessage() {}

func (x *CountPriceOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPriceOrderReq.ProtoReflect.Descriptor instead.
func (*CountPriceOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{17}
}

func (x *CountPriceOrderReq) GetGroupOrderId() uint64 {
	if x != nil {
		return x.GroupOrderId
	}
	return 0
}

func (x *CountPriceOrderReq) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CountPriceOrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupOrderId uint64  `protobuf:"varint,1,opt,name=groupOrderId,proto3" json:"groupOrderId,omitempty"`
	Price        float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CountPriceOrderRes) Reset() {
	*x = CountPriceOrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountPriceOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountPriceOrderRes) ProtoMessage() {}

func (x *CountPriceOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountPriceOrderRes.ProtoReflect.Descriptor instead.
func (*CountPriceOrderRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{18}
}

func (x *CountPriceOrderRes) GetGroupOrderId() uint64 {
	if x != nil {
		return x.GroupOrderId
	}
	return 0
}

func (x *CountPriceOrderRes) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_rpc_warehouse_proto protoreflect.FileDescriptor

var file_proto_rpc_warehouse_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x77, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x32, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x3a, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x58, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x13, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x13, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x3f, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x57, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x5b, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb2,
	0x01, 0x0a, 0x18, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x61, 0x73, 0x54, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73,
	0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x18, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x19, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5f, 0x0a, 0x19, 0x55, 0x70,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x1b, 0x44,
	0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x61, 0x0a, 0x1b, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x74, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0xa6, 0x02, 0x0a, 0x10, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x07, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x09, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x32, 0xdc,
	0x02, 0x0a, 0x16, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x07, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x09, 0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x32, 0x5e, 0x0a,
	0x11, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x67, 0x70, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_warehouse_proto_rawDescOnce sync.Once
	file_proto_rpc_warehouse_proto_rawDescData = file_proto_rpc_warehouse_proto_rawDesc
)

func file_proto_rpc_warehouse_proto_rawDescGZIP() []byte {
	file_proto_rpc_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_rpc_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_warehouse_proto_rawDescData)
	})
	return file_proto_rpc_warehouse_proto_rawDescData
}

var file_proto_rpc_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_rpc_warehouse_proto_goTypes = []interface{}{
	(*InsertWarehouseReq)(nil),          // 0: proto.InsertWarehouseReq
	(*InsertWarehouseRes)(nil),          // 1: proto.InsertWarehouseRes
	(*UpdateWarehouseReq)(nil),          // 2: proto.UpdateWarehouseReq
	(*UpdateWarehouseRes)(nil),          // 3: proto.UpdateWarehouseRes
	(*UpCountWarehouseReq)(nil),         // 4: proto.UpCountWarehouseReq
	(*UpCountWarehouseRes)(nil),         // 5: proto.UpCountWarehouseRes
	(*DownCountWarehouseReq)(nil),       // 6: proto.DownCountWarehouseReq
	(*DownCountWarehouseRes)(nil),       // 7: proto.DownCountWarehouseRes
	(*InsertTypeInWarehouseReq)(nil),    // 8: proto.InsertTypeInWarehouseReq
	(*InsertTypeInWarehouseRes)(nil),    // 9: proto.InsertTypeInWarehouseRes
	(*UpdateTypeInWarehouseReq)(nil),    // 10: proto.UpdateTypeInWarehouseReq
	(*UpdateTypeInWarehouseRes)(nil),    // 11: proto.UpdateTypeInWarehouseRes
	(*UpCountTypeInWarehouseReq)(nil),   // 12: proto.UpCountTypeInWarehouseReq
	(*UpCountTypeInWarehouseRes)(nil),   // 13: proto.UpCountTypeInWarehouseRes
	(*DownCountTypeInWarehouseReq)(nil), // 14: proto.DownCountTypeInWarehouseReq
	(*DownCountTypeInWarehouseRes)(nil), // 15: proto.DownCountTypeInWarehouseRes
	(*Order)(nil),                       // 16: proto.Order
	(*CountPriceOrderReq)(nil),          // 17: proto.CountPriceOrderReq
	(*CountPriceOrderRes)(nil),          // 18: proto.CountPriceOrderRes
}
var file_proto_rpc_warehouse_proto_depIdxs = []int32{
	16, // 0: proto.CountPriceOrderReq.orders:type_name -> proto.Order
	0,  // 1: proto.WarehouseService.Insert:input_type -> proto.InsertWarehouseReq
	2,  // 2: proto.WarehouseService.Update:input_type -> proto.UpdateWarehouseReq
	4,  // 3: proto.WarehouseService.UpCount:input_type -> proto.UpCountWarehouseReq
	6,  // 4: proto.WarehouseService.DownCount:input_type -> proto.DownCountWarehouseReq
	8,  // 5: proto.TypeInWarehouseService.Insert:input_type -> proto.InsertTypeInWarehouseReq
	10, // 6: proto.TypeInWarehouseService.Update:input_type -> proto.UpdateTypeInWarehouseReq
	12, // 7: proto.TypeInWarehouseService.UpCount:input_type -> proto.UpCountTypeInWarehouseReq
	14, // 8: proto.TypeInWarehouseService.DownCount:input_type -> proto.DownCountTypeInWarehouseReq
	17, // 9: proto.CountPriceService.CountPriceOrder:input_type -> proto.CountPriceOrderReq
	1,  // 10: proto.WarehouseService.Insert:output_type -> proto.InsertWarehouseRes
	3,  // 11: proto.WarehouseService.Update:output_type -> proto.UpdateWarehouseRes
	5,  // 12: proto.WarehouseService.UpCount:output_type -> proto.UpCountWarehouseRes
	7,  // 13: proto.WarehouseService.DownCount:output_type -> proto.DownCountWarehouseRes
	9,  // 14: proto.TypeInWarehouseService.Insert:output_type -> proto.InsertTypeInWarehouseRes
	11, // 15: proto.TypeInWarehouseService.Update:output_type -> proto.UpdateTypeInWarehouseRes
	13, // 16: proto.TypeInWarehouseService.UpCount:output_type -> proto.UpCountTypeInWarehouseRes
	15, // 17: proto.TypeInWarehouseService.DownCount:output_type -> proto.DownCountTypeInWarehouseRes
	18, // 18: proto.CountPriceService.CountPriceOrder:output_type -> proto.CountPriceOrderRes
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rpc_warehouse_proto_init() }
func file_proto_rpc_warehouse_proto_init() {
	if File_proto_rpc_warehouse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_warehouse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpCountWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpCountWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownCountWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownCountWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTypeInWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTypeInWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTypeInWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTypeInWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpCountTypeInWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpCountTypeInWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownCountTypeInWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownCountTypeInWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountPriceOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountPriceOrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_warehouse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_rpc_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_rpc_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_rpc_warehouse_proto_msgTypes,
	}.Build()
	File_proto_rpc_warehouse_proto = out.File
	file_proto_rpc_warehouse_proto_rawDesc = nil
	file_proto_rpc_warehouse_proto_goTypes = nil
	file_proto_rpc_warehouse_proto_depIdxs = nil
}
