// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/rpc_warehouse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertWarehouseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *InsertWarehouseReq) Reset() {
	*x = InsertWarehouseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertWarehouseReq) ProtoMessage() {}

func (x *InsertWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertWarehouseReq.ProtoReflect.Descriptor instead.
func (*InsertWarehouseReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *InsertWarehouseReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type InsertWarehouseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Count     uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InsertWarehouseRes) Reset() {
	*x = InsertWarehouseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_warehouse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertWarehouseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertWarehouseRes) ProtoMessage() {}

func (x *InsertWarehouseRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_warehouse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertWarehouseRes.ProtoReflect.Descriptor instead.
func (*InsertWarehouseRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *InsertWarehouseRes) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertWarehouseRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InsertWarehouseRes) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_rpc_warehouse_proto protoreflect.FileDescriptor

var file_proto_rpc_warehouse_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x77, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x32, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x32, 0x5d, 0x0a, 0x10, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x67, 0x70, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_warehouse_proto_rawDescOnce sync.Once
	file_proto_rpc_warehouse_proto_rawDescData = file_proto_rpc_warehouse_proto_rawDesc
)

func file_proto_rpc_warehouse_proto_rawDescGZIP() []byte {
	file_proto_rpc_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_rpc_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_warehouse_proto_rawDescData)
	})
	return file_proto_rpc_warehouse_proto_rawDescData
}

var file_proto_rpc_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rpc_warehouse_proto_goTypes = []interface{}{
	(*InsertWarehouseReq)(nil), // 0: proto.InsertWarehouseReq
	(*InsertWarehouseRes)(nil), // 1: proto.InsertWarehouseRes
}
var file_proto_rpc_warehouse_proto_depIdxs = []int32{
	0, // 0: proto.WarehouseService.InsertWarehouse:input_type -> proto.InsertWarehouseReq
	1, // 1: proto.WarehouseService.InsertWarehouse:output_type -> proto.InsertWarehouseRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_warehouse_proto_init() }
func file_proto_rpc_warehouse_proto_init() {
	if File_proto_rpc_warehouse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_warehouse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertWarehouseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_warehouse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertWarehouseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_warehouse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_rpc_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_rpc_warehouse_proto_msgTypes,
	}.Build()
	File_proto_rpc_warehouse_proto = out.File
	file_proto_rpc_warehouse_proto_rawDesc = nil
	file_proto_rpc_warehouse_proto_goTypes = nil
	file_proto_rpc_warehouse_proto_depIdxs = nil
}
