// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/rpc_warehouse.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WarehouseServiceClient is the client API for WarehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseServiceClient interface {
	Insert(ctx context.Context, in *InsertWarehouseReq, opts ...grpc.CallOption) (*InsertWarehouseRes, error)
	Update(ctx context.Context, in *UpdateWarehouseReq, opts ...grpc.CallOption) (*UpdateWarehouseRes, error)
	UpCount(ctx context.Context, in *UpCountWarehouseReq, opts ...grpc.CallOption) (*UpCountWarehouseRes, error)
	DownCount(ctx context.Context, in *DownCountWarehouseReq, opts ...grpc.CallOption) (*DownCountWarehouseRes, error)
}

type warehouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseServiceClient(cc grpc.ClientConnInterface) WarehouseServiceClient {
	return &warehouseServiceClient{cc}
}

func (c *warehouseServiceClient) Insert(ctx context.Context, in *InsertWarehouseReq, opts ...grpc.CallOption) (*InsertWarehouseRes, error) {
	out := new(InsertWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.WarehouseService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) Update(ctx context.Context, in *UpdateWarehouseReq, opts ...grpc.CallOption) (*UpdateWarehouseRes, error) {
	out := new(UpdateWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.WarehouseService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) UpCount(ctx context.Context, in *UpCountWarehouseReq, opts ...grpc.CallOption) (*UpCountWarehouseRes, error) {
	out := new(UpCountWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.WarehouseService/UpCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) DownCount(ctx context.Context, in *DownCountWarehouseReq, opts ...grpc.CallOption) (*DownCountWarehouseRes, error) {
	out := new(DownCountWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.WarehouseService/DownCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseServiceServer is the server API for WarehouseService service.
// All implementations must embed UnimplementedWarehouseServiceServer
// for forward compatibility
type WarehouseServiceServer interface {
	Insert(context.Context, *InsertWarehouseReq) (*InsertWarehouseRes, error)
	Update(context.Context, *UpdateWarehouseReq) (*UpdateWarehouseRes, error)
	UpCount(context.Context, *UpCountWarehouseReq) (*UpCountWarehouseRes, error)
	DownCount(context.Context, *DownCountWarehouseReq) (*DownCountWarehouseRes, error)
	mustEmbedUnimplementedWarehouseServiceServer()
}

// UnimplementedWarehouseServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWarehouseServiceServer struct {
}

func (UnimplementedWarehouseServiceServer) Insert(context.Context, *InsertWarehouseReq) (*InsertWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedWarehouseServiceServer) Update(context.Context, *UpdateWarehouseReq) (*UpdateWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedWarehouseServiceServer) UpCount(context.Context, *UpCountWarehouseReq) (*UpCountWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpCount not implemented")
}
func (UnimplementedWarehouseServiceServer) DownCount(context.Context, *DownCountWarehouseReq) (*DownCountWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownCount not implemented")
}
func (UnimplementedWarehouseServiceServer) mustEmbedUnimplementedWarehouseServiceServer() {}

// UnsafeWarehouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseServiceServer will
// result in compilation errors.
type UnsafeWarehouseServiceServer interface {
	mustEmbedUnimplementedWarehouseServiceServer()
}

func RegisterWarehouseServiceServer(s grpc.ServiceRegistrar, srv WarehouseServiceServer) {
	s.RegisterService(&WarehouseService_ServiceDesc, srv)
}

func _WarehouseService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WarehouseService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).Insert(ctx, req.(*InsertWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WarehouseService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).Update(ctx, req.(*UpdateWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_UpCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpCountWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).UpCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WarehouseService/UpCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).UpCount(ctx, req.(*UpCountWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_DownCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownCountWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).DownCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WarehouseService/DownCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).DownCount(ctx, req.(*DownCountWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseService_ServiceDesc is the grpc.ServiceDesc for WarehouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WarehouseService",
	HandlerType: (*WarehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _WarehouseService_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _WarehouseService_Update_Handler,
		},
		{
			MethodName: "UpCount",
			Handler:    _WarehouseService_UpCount_Handler,
		},
		{
			MethodName: "DownCount",
			Handler:    _WarehouseService_DownCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc_warehouse.proto",
}

// TypeInWarehouseServiceClient is the client API for TypeInWarehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypeInWarehouseServiceClient interface {
	Insert(ctx context.Context, in *InsertTypeInWarehouseReq, opts ...grpc.CallOption) (*InsertTypeInWarehouseRes, error)
	Update(ctx context.Context, in *UpdateTypeInWarehouseReq, opts ...grpc.CallOption) (*UpdateTypeInWarehouseRes, error)
	UpCount(ctx context.Context, in *UpCountTypeInWarehouseReq, opts ...grpc.CallOption) (*UpCountTypeInWarehouseRes, error)
	DownCount(ctx context.Context, in *DownCountTypeInWarehouseReq, opts ...grpc.CallOption) (*DownCountTypeInWarehouseRes, error)
}

type typeInWarehouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTypeInWarehouseServiceClient(cc grpc.ClientConnInterface) TypeInWarehouseServiceClient {
	return &typeInWarehouseServiceClient{cc}
}

func (c *typeInWarehouseServiceClient) Insert(ctx context.Context, in *InsertTypeInWarehouseReq, opts ...grpc.CallOption) (*InsertTypeInWarehouseRes, error) {
	out := new(InsertTypeInWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.TypeInWarehouseService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeInWarehouseServiceClient) Update(ctx context.Context, in *UpdateTypeInWarehouseReq, opts ...grpc.CallOption) (*UpdateTypeInWarehouseRes, error) {
	out := new(UpdateTypeInWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.TypeInWarehouseService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeInWarehouseServiceClient) UpCount(ctx context.Context, in *UpCountTypeInWarehouseReq, opts ...grpc.CallOption) (*UpCountTypeInWarehouseRes, error) {
	out := new(UpCountTypeInWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.TypeInWarehouseService/UpCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeInWarehouseServiceClient) DownCount(ctx context.Context, in *DownCountTypeInWarehouseReq, opts ...grpc.CallOption) (*DownCountTypeInWarehouseRes, error) {
	out := new(DownCountTypeInWarehouseRes)
	err := c.cc.Invoke(ctx, "/proto.TypeInWarehouseService/DownCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypeInWarehouseServiceServer is the server API for TypeInWarehouseService service.
// All implementations must embed UnimplementedTypeInWarehouseServiceServer
// for forward compatibility
type TypeInWarehouseServiceServer interface {
	Insert(context.Context, *InsertTypeInWarehouseReq) (*InsertTypeInWarehouseRes, error)
	Update(context.Context, *UpdateTypeInWarehouseReq) (*UpdateTypeInWarehouseRes, error)
	UpCount(context.Context, *UpCountTypeInWarehouseReq) (*UpCountTypeInWarehouseRes, error)
	DownCount(context.Context, *DownCountTypeInWarehouseReq) (*DownCountTypeInWarehouseRes, error)
	mustEmbedUnimplementedTypeInWarehouseServiceServer()
}

// UnimplementedTypeInWarehouseServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTypeInWarehouseServiceServer struct {
}

func (UnimplementedTypeInWarehouseServiceServer) Insert(context.Context, *InsertTypeInWarehouseReq) (*InsertTypeInWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedTypeInWarehouseServiceServer) Update(context.Context, *UpdateTypeInWarehouseReq) (*UpdateTypeInWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTypeInWarehouseServiceServer) UpCount(context.Context, *UpCountTypeInWarehouseReq) (*UpCountTypeInWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpCount not implemented")
}
func (UnimplementedTypeInWarehouseServiceServer) DownCount(context.Context, *DownCountTypeInWarehouseReq) (*DownCountTypeInWarehouseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownCount not implemented")
}
func (UnimplementedTypeInWarehouseServiceServer) mustEmbedUnimplementedTypeInWarehouseServiceServer() {
}

// UnsafeTypeInWarehouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypeInWarehouseServiceServer will
// result in compilation errors.
type UnsafeTypeInWarehouseServiceServer interface {
	mustEmbedUnimplementedTypeInWarehouseServiceServer()
}

func RegisterTypeInWarehouseServiceServer(s grpc.ServiceRegistrar, srv TypeInWarehouseServiceServer) {
	s.RegisterService(&TypeInWarehouseService_ServiceDesc, srv)
}

func _TypeInWarehouseService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTypeInWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeInWarehouseServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TypeInWarehouseService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeInWarehouseServiceServer).Insert(ctx, req.(*InsertTypeInWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeInWarehouseService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTypeInWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeInWarehouseServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TypeInWarehouseService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeInWarehouseServiceServer).Update(ctx, req.(*UpdateTypeInWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeInWarehouseService_UpCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpCountTypeInWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeInWarehouseServiceServer).UpCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TypeInWarehouseService/UpCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeInWarehouseServiceServer).UpCount(ctx, req.(*UpCountTypeInWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeInWarehouseService_DownCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownCountTypeInWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeInWarehouseServiceServer).DownCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TypeInWarehouseService/DownCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeInWarehouseServiceServer).DownCount(ctx, req.(*DownCountTypeInWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TypeInWarehouseService_ServiceDesc is the grpc.ServiceDesc for TypeInWarehouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypeInWarehouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TypeInWarehouseService",
	HandlerType: (*TypeInWarehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _TypeInWarehouseService_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TypeInWarehouseService_Update_Handler,
		},
		{
			MethodName: "UpCount",
			Handler:    _TypeInWarehouseService_UpCount_Handler,
		},
		{
			MethodName: "DownCount",
			Handler:    _TypeInWarehouseService_DownCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc_warehouse.proto",
}

// CountPriceServiceClient is the client API for CountPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CountPriceServiceClient interface {
	CountPriceOrder(ctx context.Context, in *CountPriceOrderReq, opts ...grpc.CallOption) (*CountPriceOrderRes, error)
}

type countPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCountPriceServiceClient(cc grpc.ClientConnInterface) CountPriceServiceClient {
	return &countPriceServiceClient{cc}
}

func (c *countPriceServiceClient) CountPriceOrder(ctx context.Context, in *CountPriceOrderReq, opts ...grpc.CallOption) (*CountPriceOrderRes, error) {
	out := new(CountPriceOrderRes)
	err := c.cc.Invoke(ctx, "/proto.CountPriceService/CountPriceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountPriceServiceServer is the server API for CountPriceService service.
// All implementations must embed UnimplementedCountPriceServiceServer
// for forward compatibility
type CountPriceServiceServer interface {
	CountPriceOrder(context.Context, *CountPriceOrderReq) (*CountPriceOrderRes, error)
	mustEmbedUnimplementedCountPriceServiceServer()
}

// UnimplementedCountPriceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCountPriceServiceServer struct {
}

func (UnimplementedCountPriceServiceServer) CountPriceOrder(context.Context, *CountPriceOrderReq) (*CountPriceOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountPriceOrder not implemented")
}
func (UnimplementedCountPriceServiceServer) mustEmbedUnimplementedCountPriceServiceServer() {}

// UnsafeCountPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CountPriceServiceServer will
// result in compilation errors.
type UnsafeCountPriceServiceServer interface {
	mustEmbedUnimplementedCountPriceServiceServer()
}

func RegisterCountPriceServiceServer(s grpc.ServiceRegistrar, srv CountPriceServiceServer) {
	s.RegisterService(&CountPriceService_ServiceDesc, srv)
}

func _CountPriceService_CountPriceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountPriceOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountPriceServiceServer).CountPriceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CountPriceService/CountPriceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountPriceServiceServer).CountPriceOrder(ctx, req.(*CountPriceOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CountPriceService_ServiceDesc is the grpc.ServiceDesc for CountPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CountPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CountPriceService",
	HandlerType: (*CountPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountPriceOrder",
			Handler:    _CountPriceService_CountPriceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc_warehouse.proto",
}
